/**
 * Canonical public URL helpers for memorials.
 *
 * IMPORTANT: `PUBLIC_SITE_ORIGIN` is intentionally a hardcoded production
 * origin, not derived from `$page.url.origin` or any request context. QR
 * codes generated here get printed on funeral programs and keepsake cards —
 * they must always resolve correctly, even when generated by an admin
 * working on localhost or a Vercel preview deployment.
 */
export const PUBLIC_SITE_ORIGIN = 'https://tributestream.com';

/** Builds the canonical, shareable public URL for a memorial's full slug. */
export function memorialPublicUrl(fullSlug: string | null | undefined): string {
	if (!fullSlug) return '';
	return `${PUBLIC_SITE_ORIGIN}/${fullSlug}`;
}
